stages:
    - build
    - deploy

build:
    stage: build
    tags:
        - maven
    only:
        - master
        - gitlab-ci
    script:
        - "mvn clean package -B -Dmaven.test.skip=true"
    artifacts:
        paths:
            - target/archival-*.jar

devel:
    stage: deploy
    when: manual
    dependencies:
        - build
    variables:
        SERVER_ADDR: "arclib.inqool.cz"
        SSH_PORT: "22"
    only:
        - master
        - gitlab-ci
    script:
        - "scp -P $SSH_PORT -o StrictHostKeyChecking=no target/archival-*.jar gitlab-runner@$SERVER_ADDR:/opt/storage/storage.jar"
        - "ssh -p $SSH_PORT -o StrictHostKeyChecking=no gitlab-runner@$SERVER_ADDR 'sudo systemctl restart archival-storage'"
