env: knav
server.port: 8081
spring.application.name: arcstorage
security:
  debug: true
  jwt:
    secret: YXVyYTI0Z3JvZ3M=
    expiration: 30000000
  basic:
    authQueries: "/api/user/login"
  roles:
    internal:
      enabled: true
  password:
    enabled: true
    length: 8
    digit: true
    alphabet: true
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/arcstorage
    username: arcstorage
    password: vuji61oilo
    driver-class-name: org.postgresql.Driver
    name: mainPool
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddl-auto: validate
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      use-new-id-generator-mappings: true
  http:
    multipart:
      maxFileSize: -1
      maxRequestSize: -1
  jackson:
    serialization:
      write-dates-as-timestamps: false
  mail:
    host: smtp.gmail.com
    port: 465
    username: noreply@inqool.cz
    password: blah38espro
    protocol: smtp
    properties.mail.smtp:
      auth: true
      starttls.enable: false
      ssl.trust: smtp.gmail.com
      ssl.enable: true
mail:
  sender:
    email: noreply@inqool.cz
    name: Archival Storage
  app:
    name: Archival Storage
    logo: logo.png
    link: http://arclib.inqool.cz
    url: http://arclib.inqool.cz
    path:
      tasks:
  enabled: true
liquibase:
  changeLog: classpath:/dbchangelog.arcstorage.xml
  url: jdbc:postgresql://localhost:5432/arcstorage
  user: arcstorage
  password: vuji61oilo
arcstorage:
  tmp-folder: tmp
  auth-key: src/main/resources/arcstorage.ppk
  thread-count: 8
  reserved-thread-count: 8
  connection-timeout: 5000
  state-change-transaction-timeout: 5
  synchronization-init-timeout: 15

